CHANNELS:
  CHANNEL_NAMES: null
  CHANNEL_POLICY: all
FILENAME: ./Demo/S1_ictal.edf
FILENAME_COMPARE: null
HIGHPASS: null
LOG: true
LOWPASS: null
NOTCH: null
NPERSEG: 5120
OFFSET: 0.0002
ORDER: 3
PORT: 8000
QUALITY: 30
WIN1:
- 5
- 10
WIN2:
- 35
- 120
